### ISSUE TITLE
media call results in Http(Error { kind: UrlEncoded(Custom("unsupported value")), url: None })

### ISSUE THREAD

**Issue by bvtsang** [Aaronepower/Mammut#10]
I'm not sure if this is the best place to ask this question. If it's not, please redirect me to the appropriate place.

I'm trying to see if I can get an image attached to a post. Here is the relevant portion of my code:

```rust
let data: mammut::Data = serde_json::from_reader(deserialized)?;
let mastodon = Mastodon::from_data(data)?;

let mut image = File::open("hello-world.png")?;
let mut contents: Vec<u8> = Vec::new();
println!("read_to_end");
let read_bytes = image.read_to_end(&mut contents)?;
println!("{:?}", read_bytes);
println!("{:?}", mastodon);
println!("mastodon.media");
let attachment = mastodon.media(contents)?
```

Running this gives the following output:

```
read_to_end
2416
Mastodon { client: Client { redirect_policy: Mutex { data: RedirectPolicy { inner: Limit(10) } }, referer: AtomicBool(true), auto_ungzip: AtomicBool(true) }, headers: Headers { Authorization: Bearer redacted
, }, data: Data { base: "https://ephemeral.glitch.social", client_id: "redacted", client_secret: "redacted", redirect: "urn:ietf:wg:oauth:2.0:oob", token: "redacted" } }
mastodon.media
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Http(Error { kind: UrlEncoded(Custom("unsupported value")), url: None })', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: xumbot::main
             at ./src/main.rs:19
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  14: main
  15: __libc_start_main
  16: _start
```

I think this error has something to do with the macros `mammut` uses to handle REST calls, but I'm not quite sure how to figure out what specifically is wrong.

I was able to use the API to post a status with only text, and according to the output I am able to load the contents of my image into a `Vec<u8>`. But my code fails when `let attachment = mastodon.media(contents)?` is executed.

Am I using the API incorrectly? Is there something else I'm missing?

**Comment by Aaronepower** [comment]
Thanks for the issue! This is a perfectly fine place to ask. I don't think you are using the API incorrectly, I'll look into the problem.

**Comment by Aaronepower** [comment]
Sorry this has taken so long to resolve, I've been quite busy and reqwest was missing a feature to implement it properly. I can now confirm it works in 0.9
